// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type AgentConfigRepository interface {
	Create(ctx context.Context, userID uuid.UUID, agentConfig *models.AgentConfig) (*models.AgentConfig, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.AgentConfig, error)
	FindByID(ctx context.Context, userID uuid.UUID, agentConfigID uuid.UUID) (*models.AgentConfig, error)
	FindByUserID(ctx context.Context, userID uuid.UUID) (*models.AgentConfig, error)
	Update(ctx context.Context, userID uuid.UUID, agentConfig *models.AgentConfig) (*models.AgentConfig, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, agentConfigID uuid.UUID, agentConfig *models.AgentConfig, fields *AgentConfigUpdateFields) (*models.AgentConfig, error)
	Delete(ctx context.Context, userID uuid.UUID, agentConfigID uuid.UUID) error
}

type AgentConfigUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewAgentConfigUpdateFields() *AgentConfigUpdateFields {
	return &AgentConfigUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *AgentConfigUpdateFields) SystemPrompt() *AgentConfigUpdateFields {
	return f.add("system_prompt")
}

func (f *AgentConfigUpdateFields) Temperature() *AgentConfigUpdateFields {
	return f.add("temperature")
}

func (f *AgentConfigUpdateFields) EnableKnowledge() *AgentConfigUpdateFields {
	return f.add("enable_knowledge")
}

func (f *AgentConfigUpdateFields) EnableMemory() *AgentConfigUpdateFields {
	return f.add("enable_memory")
}

func (f *AgentConfigUpdateFields) EnableWebSearch() *AgentConfigUpdateFields {
	return f.add("enable_web_search")
}

func (f *AgentConfigUpdateFields) EnableActiveRecall() *AgentConfigUpdateFields {
	return f.add("enable_active_recall")
}

func (f *AgentConfigUpdateFields) EnableCrossSession() *AgentConfigUpdateFields {
	return f.add("enable_cross_session")
}

func (f *AgentConfigUpdateFields) ShowAvatar() *AgentConfigUpdateFields {
	return f.add("show_avatar")
}

func (f *AgentConfigUpdateFields) HumanMode() *AgentConfigUpdateFields {
	return f.add("human_mode")
}

func (f *AgentConfigUpdateFields) ContextEnabled() *AgentConfigUpdateFields {
	return f.add("context_enabled")
}

func (f *AgentConfigUpdateFields) ContextWindowTokens() *AgentConfigUpdateFields {
	return f.add("context_window_tokens")
}

func (f *AgentConfigUpdateFields) ContextOutputReserveTokens() *AgentConfigUpdateFields {
	return f.add("context_output_reserve_tokens")
}

func (f *AgentConfigUpdateFields) ContextSafetyMarginTokens() *AgentConfigUpdateFields {
	return f.add("context_safety_margin_tokens")
}

func (f *AgentConfigUpdateFields) ContextTriggerRatio() *AgentConfigUpdateFields {
	return f.add("context_trigger_ratio")
}

func (f *AgentConfigUpdateFields) ContextTargetRatio() *AgentConfigUpdateFields {
	return f.add("context_target_ratio")
}

func (f *AgentConfigUpdateFields) ContextKeepRecentTokens() *AgentConfigUpdateFields {
	return f.add("context_keep_recent_tokens")
}

func (f *AgentConfigUpdateFields) ContextSummaryMaxTokens() *AgentConfigUpdateFields {
	return f.add("context_summary_max_tokens")
}

func (f *AgentConfigUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *AgentConfigUpdateFields) add(column string) *AgentConfigUpdateFields {
	if f == nil {
		f = NewAgentConfigUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
