// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type AgentPersonaRepository interface {
	Create(ctx context.Context, userID uuid.UUID, agentPersona *models.AgentPersona) (*models.AgentPersona, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.AgentPersona, error)
	FindByID(ctx context.Context, userID uuid.UUID, agentPersonaID uuid.UUID) (*models.AgentPersona, error)
	// FindActive 返回用户当前生效的角色；不存在时返回 (nil, nil)。
	FindActive(ctx context.Context, userID uuid.UUID) (*models.AgentPersona, error)
	Update(ctx context.Context, userID uuid.UUID, agentPersona *models.AgentPersona) (*models.AgentPersona, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, agentPersonaID uuid.UUID, agentPersona *models.AgentPersona, fields *AgentPersonaUpdateFields) (*models.AgentPersona, error)
	Delete(ctx context.Context, userID uuid.UUID, agentPersonaID uuid.UUID) error
	Count(ctx context.Context, userID uuid.UUID) (int64, error)
	ActivateByID(ctx context.Context, userID uuid.UUID, personaID uuid.UUID) error
}

type AgentPersonaUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewAgentPersonaUpdateFields() *AgentPersonaUpdateFields {
	return &AgentPersonaUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *AgentPersonaUpdateFields) Name() *AgentPersonaUpdateFields {
	return f.add("name")
}

func (f *AgentPersonaUpdateFields) AvatarKey() *AgentPersonaUpdateFields {
	return f.add("avatar_key")
}

func (f *AgentPersonaUpdateFields) Identity() *AgentPersonaUpdateFields {
	return f.add("identity")
}

func (f *AgentPersonaUpdateFields) Soul() *AgentPersonaUpdateFields {
	return f.add("soul")
}

func (f *AgentPersonaUpdateFields) Temperature() *AgentPersonaUpdateFields {
	return f.add("temperature")
}

func (f *AgentPersonaUpdateFields) IsActive() *AgentPersonaUpdateFields {
	return f.add("is_active")
}

func (f *AgentPersonaUpdateFields) InGroupOnly() *AgentPersonaUpdateFields {
	return f.add("in_group_only")
}

func (f *AgentPersonaUpdateFields) Sort() *AgentPersonaUpdateFields {
	return f.add("sort")
}

func (f *AgentPersonaUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *AgentPersonaUpdateFields) add(column string) *AgentPersonaUpdateFields {
	if f == nil {
		f = NewAgentPersonaUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
