// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type DocumentRepository interface {
	Create(ctx context.Context, userID uuid.UUID, document *models.Document) (*models.Document, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.Document, error)
	FindByID(ctx context.Context, userID uuid.UUID, documentID uuid.UUID) (*models.Document, error)
	Update(ctx context.Context, userID uuid.UUID, document *models.Document) (*models.Document, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, documentID uuid.UUID, document *models.Document, fields *DocumentUpdateFields) (*models.Document, error)
	Delete(ctx context.Context, userID uuid.UUID, documentID uuid.UUID) error
}

type DocumentUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewDocumentUpdateFields() *DocumentUpdateFields {
	return &DocumentUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *DocumentUpdateFields) KBID() *DocumentUpdateFields {
	return f.add("kb_id")
}

func (f *DocumentUpdateFields) FileName() *DocumentUpdateFields {
	return f.add("file_name")
}

func (f *DocumentUpdateFields) FileExt() *DocumentUpdateFields {
	return f.add("file_ext")
}

func (f *DocumentUpdateFields) FileSize() *DocumentUpdateFields {
	return f.add("file_size")
}

func (f *DocumentUpdateFields) FileKey() *DocumentUpdateFields {
	return f.add("file_key")
}

func (f *DocumentUpdateFields) SourceType() *DocumentUpdateFields {
	return f.add("source_type")
}

func (f *DocumentUpdateFields) SourceUrl() *DocumentUpdateFields {
	return f.add("source_url")
}

func (f *DocumentUpdateFields) Status() *DocumentUpdateFields {
	return f.add("status")
}

func (f *DocumentUpdateFields) Progress() *DocumentUpdateFields {
	return f.add("progress")
}

func (f *DocumentUpdateFields) ChunkNum() *DocumentUpdateFields {
	return f.add("chunk_num")
}

func (f *DocumentUpdateFields) ErrorMsg() *DocumentUpdateFields {
	return f.add("error_msg")
}

func (f *DocumentUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *DocumentUpdateFields) add(column string) *DocumentUpdateFields {
	if f == nil {
		f = NewDocumentUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
