// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type ImageRepository interface {
	Create(ctx context.Context, userID uuid.UUID, image *models.Image) (*models.Image, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.Image, error)
	FindByID(ctx context.Context, userID uuid.UUID, imageID uuid.UUID) (*models.Image, error)
	Update(ctx context.Context, userID uuid.UUID, image *models.Image) (*models.Image, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, imageID uuid.UUID, image *models.Image, fields *ImageUpdateFields) (*models.Image, error)
	Delete(ctx context.Context, userID uuid.UUID, imageID uuid.UUID) error
}

type ImageUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewImageUpdateFields() *ImageUpdateFields {
	return &ImageUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *ImageUpdateFields) KBID() *ImageUpdateFields {
	return f.add("kb_id")
}

func (f *ImageUpdateFields) FileName() *ImageUpdateFields {
	return f.add("file_name")
}

func (f *ImageUpdateFields) FileExt() *ImageUpdateFields {
	return f.add("file_ext")
}

func (f *ImageUpdateFields) FileSize() *ImageUpdateFields {
	return f.add("file_size")
}

func (f *ImageUpdateFields) FileKey() *ImageUpdateFields {
	return f.add("file_key")
}

func (f *ImageUpdateFields) Description() *ImageUpdateFields {
	return f.add("description")
}

func (f *ImageUpdateFields) OCRText() *ImageUpdateFields {
	return f.add("ocr_text")
}

func (f *ImageUpdateFields) Objects() *ImageUpdateFields {
	return f.add("objects")
}

func (f *ImageUpdateFields) Scene() *ImageUpdateFields {
	return f.add("scene")
}

func (f *ImageUpdateFields) Status() *ImageUpdateFields {
	return f.add("status")
}

func (f *ImageUpdateFields) ErrorMsg() *ImageUpdateFields {
	return f.add("error_msg")
}

func (f *ImageUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *ImageUpdateFields) add(column string) *ImageUpdateFields {
	if f == nil {
		f = NewImageUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
