// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type KnowledgeBaseRepository interface {
	Create(ctx context.Context, userID uuid.UUID, knowledgeBase *models.KnowledgeBase) (*models.KnowledgeBase, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.KnowledgeBase, error)
	FindDefault(ctx context.Context, userID uuid.UUID) (*models.KnowledgeBase, error)
	FindByID(ctx context.Context, userID uuid.UUID, knowledgeBaseID uuid.UUID) (*models.KnowledgeBase, error)
	Update(ctx context.Context, userID uuid.UUID, knowledgeBase *models.KnowledgeBase) (*models.KnowledgeBase, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, knowledgeBaseID uuid.UUID, knowledgeBase *models.KnowledgeBase, fields *KnowledgeBaseUpdateFields) (*models.KnowledgeBase, error)
	Delete(ctx context.Context, userID uuid.UUID, knowledgeBaseID uuid.UUID) error
}

type KnowledgeBaseUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewKnowledgeBaseUpdateFields() *KnowledgeBaseUpdateFields {
	return &KnowledgeBaseUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *KnowledgeBaseUpdateFields) Name() *KnowledgeBaseUpdateFields {
	return f.add("name")
}

func (f *KnowledgeBaseUpdateFields) Description() *KnowledgeBaseUpdateFields {
	return f.add("description")
}

func (f *KnowledgeBaseUpdateFields) Icon() *KnowledgeBaseUpdateFields {
	return f.add("icon")
}

func (f *KnowledgeBaseUpdateFields) Color() *KnowledgeBaseUpdateFields {
	return f.add("color")
}

func (f *KnowledgeBaseUpdateFields) IsDefault() *KnowledgeBaseUpdateFields {
	return f.add("is_default")
}

func (f *KnowledgeBaseUpdateFields) ChatEnabled() *KnowledgeBaseUpdateFields {
	return f.add("chat_enabled")
}

func (f *KnowledgeBaseUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *KnowledgeBaseUpdateFields) add(column string) *KnowledgeBaseUpdateFields {
	if f == nil {
		f = NewKnowledgeBaseUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
