// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type MCPServerRepository interface {
	Create(ctx context.Context, userID uuid.UUID, mCPServer *models.MCPServer) (*models.MCPServer, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.MCPServer, error)
	FindByID(ctx context.Context, userID uuid.UUID, mCPServerID uuid.UUID) (*models.MCPServer, error)
	Update(ctx context.Context, userID uuid.UUID, mCPServer *models.MCPServer) (*models.MCPServer, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, mCPServerID uuid.UUID, mCPServer *models.MCPServer, fields *MCPServerUpdateFields) (*models.MCPServer, error)
	Delete(ctx context.Context, userID uuid.UUID, mCPServerID uuid.UUID) error
	FindByName(ctx context.Context, userID uuid.UUID, Name string) (*models.MCPServer, error)
}

type MCPServerUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewMCPServerUpdateFields() *MCPServerUpdateFields {
	return &MCPServerUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *MCPServerUpdateFields) Name() *MCPServerUpdateFields {
	return f.add("name")
}

func (f *MCPServerUpdateFields) Transport() *MCPServerUpdateFields {
	return f.add("transport")
}

func (f *MCPServerUpdateFields) Url() *MCPServerUpdateFields {
	return f.add("url")
}

func (f *MCPServerUpdateFields) AuthType() *MCPServerUpdateFields {
	return f.add("auth_type")
}

func (f *MCPServerUpdateFields) AuthConfig() *MCPServerUpdateFields {
	return f.add("auth_config")
}

func (f *MCPServerUpdateFields) Enabled() *MCPServerUpdateFields {
	return f.add("enabled")
}

func (f *MCPServerUpdateFields) Status() *MCPServerUpdateFields {
	return f.add("status")
}

func (f *MCPServerUpdateFields) LastError() *MCPServerUpdateFields {
	return f.add("last_error")
}

func (f *MCPServerUpdateFields) ToolsCache() *MCPServerUpdateFields {
	return f.add("tools_cache")
}

func (f *MCPServerUpdateFields) SyncedAt() *MCPServerUpdateFields {
	return f.add("synced_at")
}

func (f *MCPServerUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *MCPServerUpdateFields) add(column string) *MCPServerUpdateFields {
	if f == nil {
		f = NewMCPServerUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
