// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type TagRepository interface {
	Create(ctx context.Context, userID uuid.UUID, tag *models.Tag) (*models.Tag, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.Tag, error)
	ListByScope(ctx context.Context, userID uuid.UUID, scope string) ([]*models.Tag, error)
	PageList(ctx context.Context, userID uuid.UUID, query TagListQuery) ([]*models.Tag, int64, error)
	CountDocumentsByTags(ctx context.Context, userID uuid.UUID, tagIDs []uuid.UUID) (map[uuid.UUID]int64, error)
	CountImagesByTags(ctx context.Context, userID uuid.UUID, tagIDs []uuid.UUID) (map[uuid.UUID]int64, error)
	FindByID(ctx context.Context, userID uuid.UUID, tagID uuid.UUID) (*models.Tag, error)
	Update(ctx context.Context, userID uuid.UUID, tag *models.Tag) (*models.Tag, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, tagID uuid.UUID, tag *models.Tag, fields *TagUpdateFields) (*models.Tag, error)
	SyncDocumentTags(ctx context.Context, userID uuid.UUID, documentID uuid.UUID, names []string) ([]models.Tag, error)
	SyncImageTags(ctx context.Context, userID uuid.UUID, imageID uuid.UUID, names []string) ([]models.Tag, error)
	ListDocumentIDsByTag(ctx context.Context, userID uuid.UUID, tagID uuid.UUID) ([]uuid.UUID, error)
	ListDocumentTagNames(ctx context.Context, userID uuid.UUID, documentIDs []uuid.UUID) (map[uuid.UUID][]string, error)
	Merge(ctx context.Context, userID uuid.UUID, sourceID uuid.UUID, targetID uuid.UUID) (*models.Tag, error)
	Delete(ctx context.Context, userID uuid.UUID, tagID uuid.UUID) error
}

type TagListQuery struct {
	Scope string
	PageQuery
}

type TagUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewTagUpdateFields() *TagUpdateFields {
	return &TagUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *TagUpdateFields) Name() *TagUpdateFields {
	return f.add("name")
}

func (f *TagUpdateFields) Color() *TagUpdateFields {
	return f.add("color")
}

func (f *TagUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *TagUpdateFields) add(column string) *TagUpdateFields {
	if f == nil {
		f = NewTagUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
