// Code generated by codegen; DO NOT EDIT.

package promptsgen

// AgentOptimizePromptParams 定义 AgentOptimizePrompt 提示词允许使用的模板参数。
type AgentOptimizePromptParams struct {
	RawPrompt string
}

// AgentOptimizePrompt 使用 AgentOptimizePromptParams 渲染 agent/optimize_prompt 提示词。
func (c *Client) AgentOptimizePrompt(params *AgentOptimizePromptParams) (string, error) {
	// 生成方法只传递类型化参数，模板查找和解析统一交给 Renderer。
	return c.render("agent/optimize_prompt", params)
}
