// Code generated by codegen; DO NOT EDIT.

package promptsgen

// MemoryDedupEntityParams 定义 MemoryDedupEntity 提示词允许使用的模板参数。
type MemoryDedupEntityParams struct {
	Context *MemoryDedupEntityContext
	EntityA *MemoryDedupEntityEntityA
	EntityB *MemoryDedupEntityEntityB
}

// MemoryDedupEntityContext 定义 Context 模板字段的嵌套参数。
type MemoryDedupEntityContext struct {
	NameContains string
	NameEmbedSim string
	NameTextSim  string
}

// MemoryDedupEntityEntityA 定义 EntityA 模板字段的嵌套参数。
type MemoryDedupEntityEntityA struct {
	Aliases     []string
	Description string
	Name        string
	Type        string
}

// MemoryDedupEntityEntityB 定义 EntityB 模板字段的嵌套参数。
type MemoryDedupEntityEntityB struct {
	Aliases     []string
	Description string
	Name        string
	Type        string
}

// MemoryDedupEntity 使用 MemoryDedupEntityParams 渲染 memory/dedup_entity 提示词。
func (c *Client) MemoryDedupEntity(params *MemoryDedupEntityParams) (string, error) {
	// 生成方法只传递类型化参数，模板查找和解析统一交给 Renderer。
	return c.render("memory/dedup_entity", params)
}

// MemoryGenerateCommunityMetadataParams 定义 MemoryGenerateCommunityMetadata 提示词允许使用的模板参数。
type MemoryGenerateCommunityMetadataParams struct {
	Members []*MemoryGenerateCommunityMetadataMember
}

// MemoryGenerateCommunityMetadataMember 定义 Members 模板字段的嵌套参数。
type MemoryGenerateCommunityMetadataMember struct {
	Description string
	Name        string
}

// MemoryGenerateCommunityMetadata 使用 MemoryGenerateCommunityMetadataParams 渲染 memory/generate_community_metadata 提示词。
func (c *Client) MemoryGenerateCommunityMetadata(params *MemoryGenerateCommunityMetadataParams) (string, error) {
	// 生成方法只传递类型化参数，模板查找和解析统一交给 Renderer。
	return c.render("memory/generate_community_metadata", params)
}

// MemoryStatementExtractParams 定义 MemoryStatementExtract 提示词允许使用的模板参数。
type MemoryStatementExtractParams struct {
	Content string
	Context string
}

// MemoryStatementExtract 使用 MemoryStatementExtractParams 渲染 memory/statement_extract 提示词。
func (c *Client) MemoryStatementExtract(params *MemoryStatementExtractParams) (string, error) {
	// 生成方法只传递类型化参数，模板查找和解析统一交给 Renderer。
	return c.render("memory/statement_extract", params)
}

// MemoryTripletExtractParams 定义 MemoryTripletExtract 提示词允许使用的模板参数。
type MemoryTripletExtractParams struct {
	Context     string
	DialogAt    string
	EntityTypes []string
	InvalidAt   string
	Predicates  []string
	Statement   string
	ValidAt     string
}

// MemoryTripletExtract 使用 MemoryTripletExtractParams 渲染 memory/triplet_extract 提示词。
func (c *Client) MemoryTripletExtract(params *MemoryTripletExtractParams) (string, error) {
	// 生成方法只传递类型化参数，模板查找和解析统一交给 Renderer。
	return c.render("memory/triplet_extract", params)
}
