// Code generated by codegen; DO NOT EDIT.

package promptsgen

// SkillOptimizePromptParams 定义 SkillOptimizePrompt 提示词允许使用的模板参数。
type SkillOptimizePromptParams struct {
	RawPrompt string
}

// SkillOptimizePrompt 使用 SkillOptimizePromptParams 渲染 skill/optimize_prompt 提示词。
func (c *Client) SkillOptimizePrompt(params *SkillOptimizePromptParams) (string, error) {
	// 生成方法只传递类型化参数，模板查找和解析统一交给 Renderer。
	return c.render("skill/optimize_prompt", params)
}
