package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

const modulePath = "github.com/boxify/api-go"
const generatedHeader = "// Code generated by routegen; DO NOT EDIT."

type FileChangeKind string

const (
	FileAdded     FileChangeKind = "added"
	FileModified  FileChangeKind = "modified"
	FileSkipped   FileChangeKind = "skipped"
	FileUnchanged FileChangeKind = "unchanged"
)

type FileChange struct {
	Kind FileChangeKind
	Path string
}

type Report struct {
	Root  string
	Files []FileChange
}

func (r *Report) Add(kind FileChangeKind, path string) {
	if r.Root != "" {
		if rel, err := filepath.Rel(r.Root, path); err == nil && rel != "." && !strings.HasPrefix(rel, "..") {
			path = rel
		}
	}
	r.Files = append(r.Files, FileChange{Kind: kind, Path: filepath.ToSlash(path)})
}

func (r Report) Has(kind FileChangeKind, path string) bool {
	path = filepath.ToSlash(path)
	for _, file := range r.Files {
		if file.Kind == kind && file.Path == path {
			return true
		}
	}
	return false
}

var httpMethods = map[string]struct{}{
	"GET":    {},
	"POST":   {},
	"PUT":    {},
	"PATCH":  {},
	"DELETE": {},
}

type Directive struct {
	Input  string
	Output string
	Auth   bool
	UserID bool
	SSE    bool
}

type Route struct {
	HTTPMethod    string
	HandlerVar    string
	HandlerType   string
	HandlerMethod string
	Domain        string
	Directive     Directive
}

func main() {
	root := flag.String("root", ".", "project root")
	noColor := flag.Bool("no-color", false, "disable colored output")
	flag.Parse()

	report, err := Generate(*root)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	printReport(os.Stdout, report, !*noColor)
}

func Generate(root string) (Report, error) {
	report := Report{Root: root}
	routes, err := scanRoutes(root)
	if err != nil {
		return report, err
	}
	if len(routes) == 0 {
		return report, nil
	}

	handlers, err := scanHandlers(root)
	if err != nil {
		return report, err
	}
	logics, err := scanLogics(root)
	if err != nil {
		return report, err
	}

	routesByDomain := map[string][]Route{}
	for _, route := range routes {
		routesByDomain[route.Domain] = append(routesByDomain[route.Domain], route)
	}
	domains := make([]string, 0, len(routesByDomain))
	for domain := range routesByDomain {
		domains = append(domains, domain)
	}
	sort.Strings(domains)

	for _, domain := range domains {
		if err := generateHandler(root, domain, routesByDomain[domain], handlers, &report); err != nil {
			return report, err
		}
		for _, route := range routesByDomain[domain] {
			key := logicKey(route.Domain, route.HandlerMethod)
			if path, ok := logics[key]; ok {
				report.Add(FileSkipped, path)
				continue
			}
			if logicFileExists(root, route) {
				report.Add(FileSkipped, logicPath(root, route))
				continue
			}
			if err := generateLogic(root, route, &report); err != nil {
				return report, err
			}
			logics[key] = logicPath(root, route)
		}
	}
	return report, nil
}

func logicFileExists(root string, route Route) bool {
	_, err := os.Stat(logicPath(root, route))
	return err == nil
}

func logicPath(root string, route Route) string {
	return filepath.Join(root, "internal", "logic", route.Domain, snakeCase(route.HandlerMethod)+".go")
}

func parseDirective(line string) (Directive, bool) {
	text := strings.TrimSpace(line)
	text = strings.TrimPrefix(text, "//")
	text = strings.TrimSpace(text)
	if !strings.HasPrefix(text, "routegen:") {
		return Directive{}, false
	}
	text = strings.TrimSpace(strings.TrimPrefix(text, "routegen:"))
	var directive Directive
	for _, field := range strings.Fields(text) {
		switch {
		case field == "auth":
			directive.Auth = true
		case field == "user_id":
			directive.UserID = true
		case field == "sse":
			directive.SSE = true
		case strings.HasPrefix(field, "input="):
			directive.Input = strings.TrimPrefix(field, "input=")
		case strings.HasPrefix(field, "output="):
			directive.Output = strings.TrimPrefix(field, "output=")
		}
	}
	return directive, true
}

func scanRoutes(root string) ([]Route, error) {
	routesDir := filepath.Join(root, "internal", "transport", "http", "routes")
	entries, err := os.ReadDir(routesDir)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	var routes []Route
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(routesDir, entry.Name())
		fileRoutes, err := scanRouteFile(path)
		if err != nil {
			return nil, err
		}
		routes = append(routes, fileRoutes...)
	}
	return routes, nil
}

func scanRouteFile(path string) ([]Route, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var routes []Route
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Body == nil {
			continue
		}
		handlerTypes := handlerTypesByParam(fn)
		ast.Inspect(fn.Body, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok {
				return true
			}
			method, ok := httpMethodFromCall(call)
			if !ok || len(call.Args) < 2 {
				return true
			}
			handlerSelector, handlerIdent, ok := handlerFromRouteArgs(call.Args[1:], handlerTypes)
			if !ok {
				return true
			}
			handlerType := handlerTypes[handlerIdent.Name]
			if handlerType == "" {
				return true
			}
			directive, ok := directiveForCall(fset, file, call)
			if !ok {
				return true
			}
			routes = append(routes, Route{
				HTTPMethod:    method,
				HandlerVar:    handlerIdent.Name,
				HandlerType:   handlerType,
				HandlerMethod: handlerSelector.Sel.Name,
				Domain:        domainFromHandlerType(handlerType),
				Directive:     directive,
			})
			return true
		})
	}
	return routes, nil
}

func handlerFromRouteArgs(args []ast.Expr, handlerTypes map[string]string) (*ast.SelectorExpr, *ast.Ident, bool) {
	for _, arg := range args {
		selector, ok := arg.(*ast.SelectorExpr)
		if !ok {
			continue
		}
		ident, ok := selector.X.(*ast.Ident)
		if !ok {
			continue
		}
		if handlerTypes[ident.Name] == "" {
			continue
		}
		return selector, ident, true
	}
	return nil, nil, false
}

func handlerTypesByParam(fn *ast.FuncDecl) map[string]string {
	out := map[string]string{}
	if fn.Type.Params == nil {
		return out
	}
	for _, param := range fn.Type.Params.List {
		typeName := selectorTypeName(param.Type, "handler")
		if typeName == "" {
			continue
		}
		for _, name := range param.Names {
			out[name.Name] = typeName
		}
	}
	return out
}

func selectorTypeName(expr ast.Expr, pkg string) string {
	selector, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return ""
	}
	ident, ok := selector.X.(*ast.Ident)
	if !ok || ident.Name != pkg {
		return ""
	}
	return selector.Sel.Name
}

func httpMethodFromCall(call *ast.CallExpr) (string, bool) {
	selector, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", false
	}
	method := selector.Sel.Name
	_, ok = httpMethods[method]
	return method, ok
}

func directiveForCall(fset *token.FileSet, file *ast.File, call ast.Node) (Directive, bool) {
	callLine := fset.Position(call.Pos()).Line
	for _, group := range file.Comments {
		if fset.Position(group.End()).Line != callLine-1 {
			continue
		}
		for i := len(group.List) - 1; i >= 0; i-- {
			if directive, ok := parseDirective(group.List[i].Text); ok {
				return directive, true
			}
		}
	}
	return Directive{}, false
}

func scanHandlers(root string) (map[string]string, error) {
	handlerDir := filepath.Join(root, "internal", "transport", "http", "handler")
	out := map[string]string{}
	return out, scanGoFiles(handlerDir, func(path string, file *ast.File) {
		if strings.HasSuffix(path, "_gen.go") {
			return
		}
		for _, decl := range file.Decls {
			switch item := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range item.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if ok {
						out[typeSpec.Name.Name] = path
					}
				}
			case *ast.FuncDecl:
				if item.Recv == nil {
					out[item.Name.Name] = path
					continue
				}
				recv := receiverTypeName(item.Recv)
				if recv != "" {
					out[recv+"."+item.Name.Name] = path
				}
			}
		}
	})
}

func scanLogics(root string) (map[string]string, error) {
	logicDir := filepath.Join(root, "internal", "logic")
	out := map[string]string{}
	return out, scanGoFiles(logicDir, func(path string, file *ast.File) {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil {
				continue
			}
			recv := strings.TrimSuffix(receiverTypeName(fn.Recv), "Logic")
			if recv == "" {
				continue
			}
			out[logicKey(file.Name.Name, recv)] = path
		}
	})
}

func scanGoFiles(dir string, visit func(string, *ast.File)) error {
	if _, err := os.Stat(dir); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}
	fset := token.NewFileSet()
	return filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			return nil
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return err
		}
		visit(path, file)
		return nil
	})
}

func receiverTypeName(fields *ast.FieldList) string {
	if fields == nil || len(fields.List) == 0 {
		return ""
	}
	switch expr := fields.List[0].Type.(type) {
	case *ast.StarExpr:
		if ident, ok := expr.X.(*ast.Ident); ok {
			return ident.Name
		}
	case *ast.Ident:
		return expr.Name
	}
	return ""
}

func generateHandler(root, domain string, routes []Route, existing map[string]string, report *Report) error {
	if len(routes) == 0 {
		return nil
	}
	handlerType := routes[0].HandlerType
	var snippets []string
	generatedHandlerType := false
	if _, ok := existing[handlerType]; !ok {
		snippets = append(snippets, fmt.Sprintf(`type %[1]s struct {
	svc *svc.ServiceContext
}

func New%[1]s(svcCtx *svc.ServiceContext) %[1]s {
	return %[1]s{svc: svcCtx}
}
`, handlerType))
		existing[handlerType] = handlerPath(root, domain)
		existing["New"+handlerType] = handlerPath(root, domain)
		generatedHandlerType = true
	}
	for _, route := range routes {
		key := route.HandlerType + "." + route.HandlerMethod
		if path, ok := existing[key]; ok {
			report.Add(FileSkipped, path)
			continue
		}
		snippets = append(snippets, handlerMethodSnippet(route))
		existing[key] = handlerPath(root, domain)
	}
	if len(snippets) == 0 {
		return nil
	}

	imports := handlerImports(domain, routes, generatedHandlerType)
	body := strings.Join(snippets, "\n")
	path := handlerPath(root, domain)
	if _, err := os.Stat(path); err == nil {
		return appendGoFile(path, imports, body, report)
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	content := generatedFile("handler", imports, body, false)
	return writeGeneratedFile(path, content, report)
}

func handlerPath(root, domain string) string {
	return filepath.Join(root, "internal", "transport", "http", "handler", domain+".go")
}

func handlerImports(domain string, routes []Route, includeSvc bool) []string {
	imports := []string{
		fmt.Sprintf(`%slogic "%s/internal/logic/%s"`, domain, modulePath, domain),
		fmt.Sprintf(`"%s/internal/transport/http/response"`, modulePath),
		`"github.com/gin-gonic/gin"`,
	}
	if includeSvc {
		imports = append(imports, fmt.Sprintf(`"%s/internal/svc"`, modulePath))
	}
	needsRequest := false
	needsUtil := false
	needsXerr := false
	for _, route := range routes {
		if route.Directive.Input != "" {
			needsRequest = true
			needsXerr = true
		}
		if route.Directive.UserID {
			needsUtil = true
		}
	}
	if needsRequest {
		imports = append(imports, fmt.Sprintf(`"%s/internal/transport/http/request"`, modulePath))
	}
	if needsUtil {
		imports = append(imports, fmt.Sprintf(`"%s/internal/util"`, modulePath))
	}
	if needsXerr {
		imports = append(imports, fmt.Sprintf(`"%s/internal/xerr"`, modulePath))
	}
	sort.Strings(imports)
	return imports
}

func handlerMethodSnippet(route Route) string {
	var b strings.Builder
	fmt.Fprintf(&b, "func (h %s) %s(c *gin.Context) {\n", route.HandlerType, route.HandlerMethod)
	if route.Directive.Input != "" {
		inputVar, bindMethod := handlerInputBinding(route)
		fmt.Fprintf(&b, "\tvar %s %s\n", inputVar, route.Directive.Input)
		fmt.Fprintf(&b, "\tif err := c.%s(&%s); err != nil {\n", bindMethod, inputVar)
		b.WriteString("\t\tresponse.FromError(c, xerr.Validation(err))\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
	}
	if route.Directive.UserID {
		b.WriteString("\tuserID, err := util.UserIDFromContext(c.Request.Context())\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\tresponse.FromError(c, err)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
	}
	callArgs := handlerCallArgs(route)
	if route.Directive.SSE {
		fmt.Fprintf(&b, "\tevents, err := %slogic.New%sLogic(c.Request.Context(), h.svc).%s(%s)\n", route.Domain, route.HandlerMethod, route.HandlerMethod, strings.Join(callArgs, ", "))
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\tresponse.FromError(c, err)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\t_ = events\n")
		b.WriteString("\tresponse.OK(c, map[string]any{})\n")
		b.WriteString("}\n")
		return b.String()
	}
	if route.Directive.Output == "" {
		fmt.Fprintf(&b, "\tif err := %slogic.New%sLogic(c.Request.Context(), h.svc).%s(%s); err != nil {\n", route.Domain, route.HandlerMethod, route.HandlerMethod, strings.Join(callArgs, ", "))
		b.WriteString("\t\tresponse.FromError(c, err)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\tresponse.OK(c, nil)\n")
		b.WriteString("}\n")
		return b.String()
	}
	fmt.Fprintf(&b, "\tout, err := %slogic.New%sLogic(c.Request.Context(), h.svc).%s(%s)\n", route.Domain, route.HandlerMethod, route.HandlerMethod, strings.Join(callArgs, ", "))
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tresponse.FromError(c, err)\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tresponse.OK(c, out)\n")
	b.WriteString("}\n")
	return b.String()
}

func handlerInputBinding(route Route) (inputVar string, bindMethod string) {
	if route.HTTPMethod == "GET" {
		return "query", "ShouldBindQuery"
	}
	return "body", "ShouldBindJSON"
}

func handlerCallArgs(route Route) []string {
	var args []string
	if route.Directive.UserID {
		args = append(args, "userID")
	}
	if route.Directive.Input != "" {
		inputVar, _ := handlerInputBinding(route)
		args = append(args, "&"+inputVar)
	}
	return args
}

func generateLogic(root string, route Route, report *Report) error {
	methodArgs, imports := logicMethodArgs(route)
	output := route.Directive.Output
	body := fmt.Sprintf(`type %[1]sLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
	log    *slog.Logger
}

func New%[1]sLogic(ctx context.Context, svcCtx *svc.ServiceContext) *%[1]sLogic {
	return &%[1]sLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		log:    xlog.Component("logic.%[2]s.%[3]s"),
	}
}

func (l *%[1]sLogic) %[1]s(%[4]s) %[5]s {
	_ = l
%[6]s
}
`, route.HandlerMethod, route.Domain, strings.ToLower(route.HandlerMethod), strings.Join(methodArgs, ", "), logicReturnSignature(output), logicZeroReturn(output))

	imports = append(imports,
		`"context"`,
		`"log/slog"`,
		fmt.Sprintf(`"%s/internal/observability/xlog"`, modulePath),
		fmt.Sprintf(`"%s/internal/svc"`, modulePath),
	)
	sort.Strings(imports)
	content := generatedFile(route.Domain, imports, body, false)
	return writeGeneratedFile(logicPath(root, route), content, report)
}

func logicMethodArgs(route Route) ([]string, []string) {
	var args []string
	var imports []string
	if route.Directive.UserID {
		args = append(args, "userID uuid.UUID")
		imports = append(imports, `"github.com/google/uuid"`)
	}
	if route.Directive.Input != "" {
		args = append(args, "input *"+route.Directive.Input)
		imports = append(imports, fmt.Sprintf(`"%s/internal/transport/http/request"`, modulePath))
	}
	if strings.Contains(route.Directive.Output, "response.") {
		imports = append(imports, fmt.Sprintf(`"%s/internal/transport/http/response"`, modulePath))
	}
	return args, imports
}

func logicReturnSignature(goType string) string {
	goType = strings.TrimSpace(goType)
	if goType == "" {
		return "error"
	}
	return fmt.Sprintf("(%s, error)", logicReturnType(goType))
}

func logicReturnType(goType string) string {
	goType = strings.TrimSpace(goType)
	switch {
	case goType == "" || goType == "any":
		return "any"
	case strings.HasPrefix(goType, "*") || strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") || strings.HasPrefix(goType, "<-chan ") || strings.HasPrefix(goType, "chan "):
		return goType
	default:
		return "*" + goType
	}
}

func logicZeroReturn(goType string) string {
	goType = strings.TrimSpace(goType)
	if goType == "" {
		return "\treturn nil"
	}
	return zeroReturn(logicReturnType(goType))
}

func zeroReturn(goType string) string {
	goType = strings.TrimSpace(goType)
	switch {
	case goType == "" || goType == "any":
		return "\treturn nil, nil"
	case strings.HasPrefix(goType, "*") || strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "<-chan ") || strings.HasPrefix(goType, "chan "):
		return "\treturn nil, nil"
	case goType == "string":
		return "\treturn \"\", nil"
	case goType == "bool":
		return "\treturn false, nil"
	case isNumberType(goType):
		return "\treturn 0, nil"
	default:
		return fmt.Sprintf("\treturn %s{}, nil", goType)
	}
}

func isNumberType(goType string) bool {
	switch goType {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
		return true
	default:
		return false
	}
}

func generatedFile(pkg string, imports []string, body string, includeHeader bool) string {
	var b strings.Builder
	if includeHeader {
		b.WriteString(generatedHeader)
		b.WriteString("\n\n")
	}
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, item := range unique(imports) {
			fmt.Fprintf(&b, "\t%s\n", item)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(body)
	return b.String()
}

func writeGeneratedFile(path, content string, report *Report) error {
	formatted, err := format.Source([]byte(content))
	if err != nil {
		return fmt.Errorf("format generated file %s: %w\n%s", path, err, content)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if data, err := os.ReadFile(path); err == nil {
		if !strings.HasPrefix(string(data), generatedHeader) {
			return fmt.Errorf("refuse to overwrite non-routegen file %s", path)
		}
		if bytes.Equal(data, formatted) {
			report.Add(FileUnchanged, path)
			return nil
		}
		report.Add(FileModified, path)
		return os.WriteFile(path, formatted, 0o644)
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	report.Add(FileAdded, path)
	return os.WriteFile(path, formatted, 0o644)
}

func appendGoFile(path string, imports []string, body string, report *Report) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	withImports, err := ensureImports(data, imports)
	if err != nil {
		return err
	}
	next := strings.TrimRight(string(withImports), "\n") + "\n\n" + strings.TrimSpace(body) + "\n"
	formatted, err := format.Source([]byte(next))
	if err != nil {
		return fmt.Errorf("format appended file %s: %w\n%s", path, err, next)
	}
	if bytes.Equal(data, formatted) {
		report.Add(FileUnchanged, path)
		return nil
	}
	report.Add(FileModified, path)
	return os.WriteFile(path, formatted, 0o644)
}

func ensureImports(src []byte, imports []string) ([]byte, error) {
	imports = unique(imports)
	if len(imports) == 0 {
		return src, nil
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	existing := map[string]struct{}{}
	for _, spec := range file.Imports {
		existing[spec.Path.Value] = struct{}{}
	}
	var missing []string
	for _, item := range imports {
		_, pathValue := splitImportSpec(item)
		if pathValue == "" {
			continue
		}
		if _, ok := existing[pathValue]; ok {
			continue
		}
		missing = append(missing, item)
	}
	if len(missing) == 0 {
		return src, nil
	}

	importDecl := firstImportDecl(file)
	if importDecl == nil {
		offset := fset.Position(file.Name.End()).Offset
		block := "\n\nimport (\n"
		for _, item := range missing {
			block += "\t" + item + "\n"
		}
		block += ")\n"
		return insertAt(src, offset, block), nil
	}

	if importDecl.Lparen.IsValid() {
		offset := fset.Position(importDecl.Rparen).Offset
		block := ""
		for _, item := range missing {
			block += "\t" + item + "\n"
		}
		return insertAt(src, offset, block), nil
	}

	if len(importDecl.Specs) == 0 {
		return src, nil
	}
	spec, ok := importDecl.Specs[0].(*ast.ImportSpec)
	if !ok {
		return src, nil
	}
	start := fset.Position(importDecl.Pos()).Offset
	end := fset.Position(importDecl.End()).Offset
	block := "import (\n\t" + astImportSpec(spec) + "\n"
	for _, item := range missing {
		block += "\t" + item + "\n"
	}
	block += ")"
	return replaceRange(src, start, end, block), nil
}

func firstImportDecl(file *ast.File) *ast.GenDecl {
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if ok && gen.Tok == token.IMPORT {
			return gen
		}
	}
	return nil
}

func astImportSpec(spec *ast.ImportSpec) string {
	if spec.Name != nil {
		return spec.Name.Name + " " + spec.Path.Value
	}
	return spec.Path.Value
}

func splitImportSpec(item string) (name string, pathValue string) {
	item = strings.TrimSpace(item)
	if item == "" {
		return "", ""
	}
	if strings.HasPrefix(item, `"`) {
		return "", item
	}
	parts := strings.Fields(item)
	if len(parts) != 2 {
		return "", ""
	}
	return parts[0], parts[1]
}

func insertAt(src []byte, offset int, text string) []byte {
	out := make([]byte, 0, len(src)+len(text))
	out = append(out, src[:offset]...)
	out = append(out, text...)
	out = append(out, src[offset:]...)
	return out
}

func replaceRange(src []byte, start, end int, text string) []byte {
	out := make([]byte, 0, len(src)+len(text)-(end-start))
	out = append(out, src[:start]...)
	out = append(out, text...)
	out = append(out, src[end:]...)
	return out
}

func printReport(w io.Writer, report Report, color bool) {
	fmt.Fprintln(w, "routegen:")
	if len(report.Files) == 0 {
		fmt.Fprintln(w, colorize("  = no files changed", ansiGray, color))
		return
	}
	for _, file := range report.Files {
		symbol, colorCode := fileChangeStyle(file.Kind)
		fmt.Fprintf(w, "  %s\n", colorize(fmt.Sprintf("%s %s", symbol, file.Path), colorCode, color))
	}
}

func fileChangeStyle(kind FileChangeKind) (string, string) {
	switch kind {
	case FileAdded:
		return "+", ansiGreen
	case FileModified:
		return "~", ansiYellow
	case FileSkipped, FileUnchanged:
		return "=", ansiGray
	default:
		return "?", ansiGray
	}
}

const (
	ansiReset  = "\x1b[0m"
	ansiGreen  = "\x1b[32m"
	ansiYellow = "\x1b[33m"
	ansiGray   = "\x1b[90m"
)

func colorize(text, code string, color bool) string {
	if !color {
		return text
	}
	return code + text + ansiReset
}

func unique(items []string) []string {
	seen := map[string]struct{}{}
	var out []string
	for _, item := range items {
		if _, ok := seen[item]; ok {
			continue
		}
		seen[item] = struct{}{}
		out = append(out, item)
	}
	return out
}

func logicKey(domain, method string) string {
	return strings.ToLower(domain) + "." + strings.ToLower(method)
}

func domainFromHandlerType(handlerType string) string {
	name := strings.TrimSuffix(handlerType, "Handler")
	return strings.ToLower(name)
}

func snakeCase(value string) string {
	var b bytes.Buffer
	for i, r := range value {
		if i > 0 && unicode.IsUpper(r) {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}
