package main

import (
	"path/filepath"
	"strings"
)

const modulePath = "github.com/boxify/api-go"
const generatedHeader = "// Code generated by routegen; DO NOT EDIT."

type FileChangeKind string

const (
	FileAdded     FileChangeKind = "added"
	FileModified  FileChangeKind = "modified"
	FileSkipped   FileChangeKind = "skipped"
	FileUnchanged FileChangeKind = "unchanged"
)

type FileChange struct {
	Kind FileChangeKind
	Path string
}

type Report struct {
	Root  string
	Files []FileChange
}

func (r *Report) Add(kind FileChangeKind, path string) {
	if r.Root != "" {
		if rel, err := filepath.Rel(r.Root, path); err == nil && rel != "." && !strings.HasPrefix(rel, "..") {
			path = rel
		}
	}
	r.Files = append(r.Files, FileChange{Kind: kind, Path: filepath.ToSlash(path)})
}

func (r Report) Has(kind FileChangeKind, path string) bool {
	path = filepath.ToSlash(path)
	for _, file := range r.Files {
		if file.Kind == kind && file.Path == path {
			return true
		}
	}
	return false
}

var httpMethods = map[string]struct{}{
	"GET":    {},
	"POST":   {},
	"PUT":    {},
	"PATCH":  {},
	"DELETE": {},
}

type Directive struct {
	Input       string
	Output      string
	Description []string
	Summary     string
	Auth        bool
	UserID      bool
	SSE         bool
}

type Route struct {
	HTTPMethod    string
	Path          string
	HandlerVar    string
	HandlerType   string
	HandlerMethod string
	Domain        string
	CommentLines  []string
	Directive     Directive
}

type RequestDTO struct {
	HasJSONBody      bool
	HasMultipartBody bool
	HasDirectURI     bool
	IsURIOnly        bool
	EmbeddedURIOnly  []string
}

type requestStruct struct {
	Fields []requestField
}

type requestField struct {
	JSONTag          string
	URITag           string
	FormTag          string
	EmbeddedType     string
	HasMultipartFile bool
}
