package main

import (
	"path/filepath"
	"strings"
)

const modulePath = "github.com/boxify/api-go"
const generatedHeader = "// Code generated by codegen; DO NOT EDIT."

type GenerationMode string

const (
	ModeWrite  GenerationMode = "write"
	ModeDryRun GenerationMode = "dry-run"
	ModeCheck  GenerationMode = "check"
)

type ReportFormat string

const (
	ReportFormatText ReportFormat = "text"
	ReportFormatJSON ReportFormat = "json"
)

type FileChangeKind string

const (
	FileAdded       FileChangeKind = "added"
	FileModified    FileChangeKind = "modified"
	FileWouldAdd    FileChangeKind = "would-add"
	FileWouldModify FileChangeKind = "would-modify"
	FileDeleted     FileChangeKind = "deleted"
	FileWouldDelete FileChangeKind = "would-delete"
	FileSkipped     FileChangeKind = "skipped"
	FileUnchanged   FileChangeKind = "unchanged"
)

type FileChange struct {
	Kind FileChangeKind `json:"kind"`
	Path string         `json:"path"`
}

type Diagnostic struct {
	Level   string `json:"level"`
	Code    string `json:"code"`
	Message string `json:"message"`
	Hint    string `json:"hint,omitempty"`
	File    string `json:"file,omitempty"`
}

type Report struct {
	Root        string         `json:"-"`
	Command     string         `json:"command,omitempty"`
	Mode        GenerationMode `json:"mode,omitempty"`
	Files       []FileChange   `json:"files,omitempty"`
	Diagnostics []Diagnostic   `json:"diagnostics,omitempty"`
}

func (r *Report) Add(kind FileChangeKind, path string) {
	if r.Root != "" {
		if rel, err := filepath.Rel(r.Root, path); err == nil && rel != "." && !strings.HasPrefix(rel, "..") {
			path = rel
		}
	}
	r.Files = append(r.Files, FileChange{Kind: kind, Path: filepath.ToSlash(path)})
}

func (r *Report) AddDiagnostic(level string, code string, message string, hint string, file string) {
	if r.Root != "" && file != "" {
		if rel, err := filepath.Rel(r.Root, file); err == nil && rel != "." && !strings.HasPrefix(rel, "..") {
			file = rel
		}
	}
	r.Diagnostics = append(r.Diagnostics, Diagnostic{
		Level:   level,
		Code:    code,
		Message: message,
		Hint:    hint,
		File:    filepath.ToSlash(file),
	})
}

func (r Report) Has(kind FileChangeKind, path string) bool {
	path = filepath.ToSlash(path)
	for _, file := range r.Files {
		if file.Kind == kind && file.Path == path {
			return true
		}
	}
	return false
}

func (r Report) HasDiagnostic(code string) bool {
	for _, item := range r.Diagnostics {
		if item.Code == code {
			return true
		}
	}
	return false
}

func (r Report) Changed() bool {
	for _, file := range r.Files {
		switch file.Kind {
		case FileAdded, FileModified, FileWouldAdd, FileWouldModify, FileDeleted, FileWouldDelete:
			return true
		}
	}
	return false
}

func (r Report) IsPreview() bool {
	return r.Mode == ModeDryRun || r.Mode == ModeCheck
}

var httpMethods = map[string]struct{}{
	"GET":    {},
	"POST":   {},
	"PUT":    {},
	"PATCH":  {},
	"DELETE": {},
}

type RouteOptions struct {
	Root    string
	DryRun  bool
	Check   bool
	Verbose bool
}

type DocsOptions struct {
	Root    string
	Output  string
	Title   string
	Version string
	DryRun  bool
	Check   bool
	Verbose bool
}

type PromptOptions struct {
	Root    string
	Output  string
	DryRun  bool
	Check   bool
	Verbose bool
}

type Directive struct {
	Input       string
	Output      string
	Event       string
	Description []string
	Summary     string
	Tag         string
	Auth        bool
	UserID      bool
	SSE         bool
}

type Route struct {
	HTTPMethod    string
	Path          string
	HandlerVar    string
	HandlerType   string
	HandlerMethod string
	Domain        string
	CommentLines  []string
	Directive     Directive
}

type RequestDTO struct {
	HasJSONBody      bool
	HasMultipartBody bool
	HasDirectURI     bool
	IsURIOnly        bool
	EmbeddedURIOnly  []string
}

type requestStruct struct {
	Fields []requestField
}

type requestField struct {
	JSONTag          string
	URITag           string
	FormTag          string
	EmbeddedType     string
	HasMultipartFile bool
}

type RepositoryOptions struct {
	Root    string
	Model   string
	Label   string
	Scope   string
	DryRun  bool
	Check   bool
	Verbose bool
}

type DoctorOptions struct {
	Root    string
	Verbose bool
}

type RouteListItem struct {
	HTTPMethod    string `json:"method"`
	Path          string `json:"path"`
	Handler       string `json:"handler"`
	Input         string `json:"input,omitempty"`
	Output        string `json:"output,omitempty"`
	Event         string `json:"event,omitempty"`
	SSE           bool   `json:"sse,omitempty"`
	HandlerExists bool   `json:"handler_exists"`
	LogicExists   bool   `json:"logic_exists"`
}

type RepositoryModelItem struct {
	Model          string `json:"model"`
	Scope          string `json:"scope"`
	RequiresScope  bool   `json:"requires_scope"`
	HasID          bool   `json:"has_id"`
	HasUserID      bool   `json:"has_user_id"`
	SuggestedScope string `json:"suggested_scope,omitempty"`
}

type RepositoryScope struct {
	Kind        string
	LocalColumn string
	JoinTable   string
	JoinColumn  string
	UserColumn  string
}

type ModelInfo struct {
	Name         string
	Fields       []ModelField
	HasID        bool
	HasUserID    bool
	HasCreatedAt bool
	HasUpdatedAt bool
}

type ModelField struct {
	Name   string
	Type   string
	Column string
}
