// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function GetAppInfo(): $CancellablePromise<domain$0.AppInfo> {
    return $Call.ByID(2660425932).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = domain$0.AppInfo.createFrom;
