// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ImageRepository struct {
	db *gorm.DB
}

func NewImageRepository(db *gorm.DB) repository.ImageRepository {
	return &ImageRepository{db: db}
}

func (r *ImageRepository) Create(ctx context.Context, userID uuid.UUID, image *models.Image) (*models.Image, error) {
	image.UserID = userID
	if err := r.db.WithContext(ctx).Create(image).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建图片元数据失败")
	}
	return image, nil
}

func (r *ImageRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.Image, error) {
	var rows []*models.Image

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询图片元数据列表失败")
	}

	return rows, nil
}

func (r *ImageRepository) CountByKnowledgeBase(ctx context.Context, userID uuid.UUID, kbIDs []uuid.UUID) (map[uuid.UUID]int64, error) {
	out := map[uuid.UUID]int64{}
	if len(kbIDs) == 0 {
		return out, nil
	}
	var rows []struct {
		KBID  uuid.UUID `gorm:"column:kb_id"`
		Count int64     `gorm:"column:item_count"`
	}
	err := r.db.WithContext(ctx).
		Model(&models.Image{}).
		Select("kb_id, COUNT(*) AS item_count").
		Where("user_id = ? AND kb_id IN ?", userID, kbIDs).
		Group("kb_id").
		Scan(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "统计知识库图片数量失败")
	}
	for _, row := range rows {
		out[row.KBID] = row.Count
	}
	return out, nil
}

func (r *ImageRepository) FindByID(ctx context.Context, userID uuid.UUID, imageID uuid.UUID) (*models.Image, error) {
	image := &models.Image{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", imageID, userID).
		First(image).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("图片元数据不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询图片元数据失败")
	}
	return image, nil
}

func (r *ImageRepository) Update(ctx context.Context, userID uuid.UUID, image *models.Image) (*models.Image, error) {
	result := r.db.WithContext(ctx).
		Model(&models.Image{}).
		Where("id = ? AND user_id = ?", image.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(image)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新图片元数据失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("图片元数据不存在")
	}
	return r.FindByID(ctx, userID, image.ID)
}

func (r *ImageRepository) UpdateFields(ctx context.Context, userID uuid.UUID, imageID uuid.UUID, image *models.Image, fields *repository.ImageUpdateFields) (*models.Image, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.Image{}).
		Where("id = ? AND user_id = ?", imageID, userID).
		Select(columns).
		Updates(image)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新图片元数据失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("图片元数据不存在")
	}
	return r.FindByID(ctx, userID, imageID)
}

func (r *ImageRepository) Delete(ctx context.Context, userID uuid.UUID, imageID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", imageID, userID).
		Delete(&models.Image{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除图片元数据失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("图片元数据不存在")
	}
	return nil
}
