// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type MCPServerRepository struct {
	db *gorm.DB
}

func NewMCPServerRepository(db *gorm.DB) repository.MCPServerRepository {
	return &MCPServerRepository{db: db}
}

func (r *MCPServerRepository) Create(ctx context.Context, userID uuid.UUID, mCPServer *models.MCPServer) (*models.MCPServer, error) {
	mCPServer.UserID = userID
	if err := r.db.WithContext(ctx).Create(mCPServer).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建MCP服务失败")
	}
	return mCPServer, nil
}

func (r *MCPServerRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.MCPServer, error) {
	var rows []*models.MCPServer

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询MCP服务列表失败")
	}

	return rows, nil
}

func (r *MCPServerRepository) FindByID(ctx context.Context, userID uuid.UUID, mCPServerID uuid.UUID) (*models.MCPServer, error) {
	mCPServer := &models.MCPServer{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", mCPServerID, userID).
		First(mCPServer).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("MCP服务不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询MCP服务失败")
	}
	return mCPServer, nil
}

func (r *MCPServerRepository) Update(ctx context.Context, userID uuid.UUID, mCPServer *models.MCPServer) (*models.MCPServer, error) {
	result := r.db.WithContext(ctx).
		Model(&models.MCPServer{}).
		Where("id = ? AND user_id = ?", mCPServer.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(mCPServer)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新MCP服务失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("MCP服务不存在")
	}
	return r.FindByID(ctx, userID, mCPServer.ID)
}

func (r *MCPServerRepository) UpdateFields(ctx context.Context, userID uuid.UUID, mCPServerID uuid.UUID, mCPServer *models.MCPServer, fields *repository.MCPServerUpdateFields) (*models.MCPServer, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.MCPServer{}).
		Where("id = ? AND user_id = ?", mCPServerID, userID).
		Select(columns).
		Updates(mCPServer)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新MCP服务失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("MCP服务不存在")
	}
	return r.FindByID(ctx, userID, mCPServerID)
}

func (r *MCPServerRepository) Delete(ctx context.Context, userID uuid.UUID, mCPServerID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", mCPServerID, userID).
		Delete(&models.MCPServer{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除MCP服务失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("MCP服务不存在")
	}
	return nil
}

func (r *MCPServerRepository) FindByName(ctx context.Context, userID uuid.UUID, Name string) (*models.MCPServer, error) {
	mCPServer := &models.MCPServer{}
	err := r.db.WithContext(ctx).
		Where("name = ? AND user_id = ?", Name, userID).
		First(mCPServer).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("MCP服务不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询MCP服务失败")
	}
	return mCPServer, nil
}
