// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type MessageRepository struct {
	db *gorm.DB
}

func NewMessageRepository(db *gorm.DB) repository.MessageRepository {
	return &MessageRepository{db: db}
}

func (r *MessageRepository) Create(ctx context.Context, userID uuid.UUID, message *models.Message) (*models.Message, error) {
	var scopeCount int64
	if err := r.db.WithContext(ctx).
		Table("conversations").
		Where("id = ? AND user_id = ?", message.ConversationID, userID).
		Count(&scopeCount).Error; err != nil {
		return nil, xerr.Wrapf(err, "校验数据归属失败")
	}
	if scopeCount == 0 {
		return nil, xerr.NotFound("消息不存在")
	}
	if err := r.db.WithContext(ctx).Create(message).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建消息失败")
	}
	return message, nil
}

func (r *MessageRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.Message, error) {
	var rows []*models.Message

	err := r.db.WithContext(ctx).
		Joins("JOIN conversations ON messages.conversation_id = conversations.id").
		Where("conversations.user_id = ?", userID).
		Order("created_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询消息列表失败")
	}

	return rows, nil
}

func (r *MessageRepository) ListByConversationID(ctx context.Context, userID uuid.UUID, conversationID uuid.UUID) ([]*models.Message, error) {
	var rows []*models.Message

	err := r.db.WithContext(ctx).
		Joins("JOIN conversations ON messages.conversation_id = conversations.id").
		Where("messages.conversation_id = ?", conversationID).
		Where("conversations.user_id = ?", userID).
		Order("messages.created_at ASC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询会话消息列表失败")
	}

	return rows, nil
}

// ListPage 按 before 游标返回一页会话消息（ASC），并报告是否还有更早消息。
func (r *MessageRepository) ListPage(ctx context.Context, userID uuid.UUID, query repository.MessageListQuery) ([]*models.Message, bool, error) {
	limit := query.Limit
	if limit < 1 {
		limit = 30
	}

	db := r.db.WithContext(ctx).
		Model(&models.Message{}).
		Joins("JOIN conversations ON messages.conversation_id = conversations.id").
		Where("messages.conversation_id = ?", query.ConversationID).
		Where("conversations.user_id = ?", userID)

	// 解析 before 锚点，使用 (created_at, id) 复合游标保证稳定分页
	if query.BeforeID != nil {
		var cursor models.Message
		err := r.db.WithContext(ctx).
			Model(&models.Message{}).
			Joins("JOIN conversations ON messages.conversation_id = conversations.id").
			Where("messages.id = ?", *query.BeforeID).
			Where("messages.conversation_id = ?", query.ConversationID).
			Where("conversations.user_id = ?", userID).
			First(&cursor).Error
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, false, xerr.BadRequest("before 消息不存在或不属于该会话")
		}
		if err != nil {
			return nil, false, xerr.Wrapf(err, "解析消息游标失败")
		}
		db = db.Where(
			"(messages.created_at < ? OR (messages.created_at = ? AND messages.id < ?))",
			cursor.CreatedAt, cursor.CreatedAt, cursor.ID,
		)
	}

	var rows []*models.Message
	// 多取一条用于判断 has_more，再按时间倒序取靠近游标/最新的一侧
	err := db.Order("messages.created_at DESC, messages.id DESC").
		Limit(limit + 1).
		Find(&rows).Error
	if err != nil {
		return nil, false, xerr.Wrapf(err, "查询会话消息分页失败")
	}

	hasMore := len(rows) > limit
	if hasMore {
		rows = rows[:limit]
	}

	// 反转为 ASC，方便前端直接渲染或 prepend
	for i, j := 0, len(rows)-1; i < j; i, j = i+1, j-1 {
		rows[i], rows[j] = rows[j], rows[i]
	}

	return rows, hasMore, nil
}

func (r *MessageRepository) FindByID(ctx context.Context, userID uuid.UUID, messageID uuid.UUID) (*models.Message, error) {
	message := &models.Message{}
	err := r.db.WithContext(ctx).
		Joins("JOIN conversations ON messages.conversation_id = conversations.id").
		Where("messages.id = ?", messageID).
		Where("conversations.user_id = ?", userID).
		First(message).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("消息不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询消息失败")
	}
	return message, nil
}

func (r *MessageRepository) Update(ctx context.Context, userID uuid.UUID, message *models.Message) (*models.Message, error) {
	result := r.db.WithContext(ctx).
		Model(&models.Message{}).
		Where("id = ?", message.ID).
		Where("EXISTS (SELECT 1 FROM conversations WHERE conversations.id = messages.conversation_id AND conversations.user_id = ?)", userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(message)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新消息失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("消息不存在")
	}
	return r.FindByID(ctx, userID, message.ID)
}

func (r *MessageRepository) UpdateFields(ctx context.Context, userID uuid.UUID, messageID uuid.UUID, message *models.Message, fields *repository.MessageUpdateFields) (*models.Message, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.Message{}).
		Where("id = ?", messageID).
		Where("EXISTS (SELECT 1 FROM conversations WHERE conversations.id = messages.conversation_id AND conversations.user_id = ?)", userID).
		Select(columns).
		Updates(message)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新消息失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("消息不存在")
	}
	return r.FindByID(ctx, userID, messageID)
}

func (r *MessageRepository) Delete(ctx context.Context, userID uuid.UUID, messageID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ?", messageID).
		Where("EXISTS (SELECT 1 FROM conversations WHERE conversations.id = messages.conversation_id AND conversations.user_id = ?)", userID).
		Delete(&models.Message{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除消息失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("消息不存在")
	}
	return nil
}

func (r *MessageRepository) Count(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	var count int64
	result := r.db.WithContext(ctx).Where("conversation_id = ?", conversationID).Model(&models.Message{}).Count(&count)
	if result.Error != nil {
		return 0, xerr.Wrapf(result.Error, "查询消息数量失败")
	}
	return count, nil
}
