// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type MessageFeedbackRepository struct {
	db *gorm.DB
}

func NewMessageFeedbackRepository(db *gorm.DB) repository.MessageFeedbackRepository {
	return &MessageFeedbackRepository{db: db}
}

func (r *MessageFeedbackRepository) Create(ctx context.Context, userID uuid.UUID, messageFeedback *models.MessageFeedback) (*models.MessageFeedback, error) {
	messageFeedback.UserID = userID
	if err := r.db.WithContext(ctx).Create(messageFeedback).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建消息反馈失败")
	}
	return messageFeedback, nil
}

func (r *MessageFeedbackRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.MessageFeedback, error) {
	var rows []*models.MessageFeedback

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询消息反馈列表失败")
	}

	return rows, nil
}

func (r *MessageFeedbackRepository) ListByConversationID(ctx context.Context, userID uuid.UUID, conversationID uuid.UUID) ([]*models.MessageFeedback, error) {
	var rows []*models.MessageFeedback

	err := r.db.WithContext(ctx).
		Where("user_id = ? and conversation_id = ?", userID, conversationID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询消息反馈列表失败")
	}

	return rows, nil
}

func (r *MessageFeedbackRepository) FindByID(ctx context.Context, userID uuid.UUID, messageFeedbackID uuid.UUID) (*models.MessageFeedback, error) {
	messageFeedback := &models.MessageFeedback{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", messageFeedbackID, userID).
		First(messageFeedback).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("消息反馈不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询消息反馈失败")
	}
	return messageFeedback, nil
}

func (r *MessageFeedbackRepository) Update(ctx context.Context, userID uuid.UUID, messageFeedback *models.MessageFeedback) (*models.MessageFeedback, error) {
	result := r.db.WithContext(ctx).
		Model(&models.MessageFeedback{}).
		Where("id = ? AND user_id = ?", messageFeedback.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(messageFeedback)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新消息反馈失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("消息反馈不存在")
	}
	return r.FindByID(ctx, userID, messageFeedback.ID)
}

func (r *MessageFeedbackRepository) UpdateFields(ctx context.Context, userID uuid.UUID, messageFeedbackID uuid.UUID, messageFeedback *models.MessageFeedback, fields *repository.MessageFeedbackUpdateFields) (*models.MessageFeedback, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.MessageFeedback{}).
		Where("id = ? AND user_id = ?", messageFeedbackID, userID).
		Select(columns).
		Updates(messageFeedback)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新消息反馈失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("消息反馈不存在")
	}
	return r.FindByID(ctx, userID, messageFeedbackID)
}

func (r *MessageFeedbackRepository) Delete(ctx context.Context, userID uuid.UUID, messageFeedbackID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", messageFeedbackID, userID).
		Delete(&models.MessageFeedback{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除消息反馈失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("消息反馈不存在")
	}
	return nil
}
