// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type TagRepository struct {
	db *gorm.DB
}

func NewTagRepository(db *gorm.DB) repository.TagRepository {
	return &TagRepository{db: db}
}

func (r *TagRepository) Create(ctx context.Context, userID uuid.UUID, tag *models.Tag) (*models.Tag, error) {
	tag.UserID = userID
	if err := r.db.WithContext(ctx).Create(tag).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建标签失败")
	}
	return tag, nil
}

func (r *TagRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.Tag, error) {
	var rows []*models.Tag

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询标签列表失败")
	}

	return rows, nil
}

func (r *TagRepository) FindByID(ctx context.Context, userID uuid.UUID, tagID uuid.UUID) (*models.Tag, error) {
	tag := &models.Tag{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", tagID, userID).
		First(tag).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("标签不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询标签失败")
	}
	return tag, nil
}

func (r *TagRepository) Update(ctx context.Context, userID uuid.UUID, tag *models.Tag) (*models.Tag, error) {
	result := r.db.WithContext(ctx).
		Model(&models.Tag{}).
		Where("id = ? AND user_id = ?", tag.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(tag)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新标签失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("标签不存在")
	}
	return r.FindByID(ctx, userID, tag.ID)
}

func (r *TagRepository) UpdateFields(ctx context.Context, userID uuid.UUID, tagID uuid.UUID, tag *models.Tag, fields *repository.TagUpdateFields) (*models.Tag, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.Tag{}).
		Where("id = ? AND user_id = ?", tagID, userID).
		Select(columns).
		Updates(tag)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新标签失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("标签不存在")
	}
	return r.FindByID(ctx, userID, tagID)
}

func (r *TagRepository) Delete(ctx context.Context, userID uuid.UUID, tagID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", tagID, userID).
		Delete(&models.Tag{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除标签失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("标签不存在")
	}
	return nil
}
